const messages = [
  "Because there are so few perfect things in this world. Even fewer that can be held so easily, or copied so well.",
  "Sponsored by alcohol",
  "James' board is planed and squared so my board must be planed, squared, and sanded.",
  "Software that makes you feel something, if only for a second",
  "Because tomorrow is almost over.",
  "Are the damned and the damnable all doomed to wander to Home Depot?",
  "It's only ghosts here in the winter.",
  "It does all the things we designed it to do.",
  "Almost as comforting as a beautiful salad bowl",
  "Now gluten free!",
  "A bi-monthly curated box of snacks",
  "Trans rights 🏳️‍⚧️",
  "Mischievous. Impish, even.",
  "Like the warm embrace of an attractive friend",
  "Served to you with grace and aplomb",
  "Hot and fresh, like a big wet bowl of soup",
  "A bell you can't unring",
  "Guaranteed not to talk about you behind your back",
  "Four naan Jeremy? Four? That's insane.",
  "<INSERT CORPORATE PROPAGANDA HERE>",
  "Mad at you because you cheated on it in a dream",
  "You could have seen it if you had been there.",
  "Spooked by its own shadow",
  "So quirky and random! Not like other software",
  "Sunflowers, bean sprouts, sweetcorn, and radishes",
  "You'll never hear from it again, save for an envelope it'll send containing fifty billion dollars and some photographs of dogs.",
  "Tastes like freedom",
  "The powerhouse of the cell",
  "Best enjoyed warm",
  "Part of a balanced breakfast",
  "Its boyfriend doesn't like art",
  "Just three kids stacked on top of each other in a trench coat",
  "It's happy, so happy, to be modern software",
  "Can we talk about the mail?",
  "The only software that celebrates Shark Week",
  "The wind — is it blowing today?",
  "Mediated through objects",
  "5'8\" in heels",
  "The kind of software teachers hang up on their walls",
  "Use it quick before it melts",
  "Rated ⭐⭐⭐⭐⭐ by all hot people",
  "Nature to advantage dressed",
  "Top ten ways to smear honey on your face",
  "Like a little lego spaceman",
  "Non-addictive",
  "Delicious and nutritious",
  "I think it's just a lens flare and some dust.",
  "Beautiful and vulnerable and power and success",
  "It knows where we keep the batteries.",
  "It goes above and beyond. It pays for parking on a Sunday.",
  "It's a shame it's not enough.",
  "they knew before me",
  "maybe tomorrow, not tonight.",
  "Powerfully disquieting",
  "Hella specific",
  "Like the lure of the sirens' song: never what it seems to be, but who among us can resist?",
  "Right where you left it",
  "super easy, barely an inconvenience",
  "fresh as the driven snow",
  "stay fresh, cheesebags!",
  "and then the funniest thing happened,",
  "Turing Complete",
  "Loves the sound of radar",
  "enough to jog the thought",
  "a little older, if not wiser",
  "it's about prawns, mark.",
  "likes it when ann reardon checks her blood",
  "knows all the words but can't hear the music",
  "a kfc chicken has everything it needs.",
  "once again, software which inexplicably wants to test your knowledge of the symptoms of rabies.",
  "Can rollerskate with grace",
  "It takes work to be a clown.",
  "just a macabre charade",
  "you can't trick an old dog",
  "it believes you now.",
  "that one egg was forty eggs?",
  "in the last act Billie Eilish sings 'What Was I Made For' and the truth is we don't know.",
  "saccharine and snide",
  "a silence which consumes the space between friends",
  "born amongst salt and smoke. like a ham.",
  "with no thrilling story to tell, and nobody to tell it to.",
  "Advocating in all the ways that it can for a world which cannot advocate for itself.",
  "colder in the summertime",
  "paints its shirt, says it's sorry, and calls its dad.",
  "as authentic or performative as is convenient.",
  "it made amends with its little found family",
  "perhaps it is unloved only for the moment.",
  "promised it would teach me how to hula hoop but never got around to it.",
  "As user-friendly as a cactus",
  "RIP Craigs 🕊️",
  "casts a shadow on its own forehead.",
  "In the world but not of it.",
  "It's only a tin full of people.",
  "How fiendishly droll",
  "Named for his uncle",
  "i saw it in a picture once.",
  "A little uneven, is all.",
  "It will pull your hair up but not out.",
  "like a wheel within a wheel",
];

export function getMotd() {
  return messages[Math.floor(Math.random() * messages.length)]!;
}
